[package]
name = "cargo-release-oxc"
version = "0.0.6"
edition = "2021"
description = "Oxc release management"
authors = ["Boshen <boshenc@gmail.com>"]
repository = "https://github.com/oxc-project/cargo-release-oxc"
keywords = []
categories = []
license = "MIT"
readme = "README.md"

[lints.clippy]
all = "warn"
pedantic = "warn"
nursery = "warn"
dbg_macro = "warn"
unwrap_used = "warn"
empty_drop = "warn"
exit = "warn"
empty_structs_with_brackets = "warn"
rc_buffer = "warn"
rc_mutex = "warn"
same_name_method = "warn"

[lib]
doctest = false

[[bin]]
name = "cargo-release-oxc"
path = "src/main.rs"
test = false

[dependencies]
anyhow = "1.0.81"
bpaf = { version = "0.9.11", features = ["derive", "batteries"] }
cargo_metadata = "0.18.1"
git-cliff-core = { version = "2.2.0", default-features = false, features = [
  "repo",
] }
glob = "0.3.1"
toml_edit = { version = "0.22.9", features = ["parse"] }
semver = "1.0.22"
git_cmd = "0.6.2"
