[package]
name = "release-oxc"
version = "0.0.0"
edition = "2021"
description = "Oxc release management"
authors = ["Boshen <boshenc@gmail.com>"]
repository = "https://github.com/Boshen/cargo-release-oxc"
keywords = []
categories = []
license = "MIT"
readme = "README.md"

[lib]
doctest = false

[[bin]]
name = "cargo-release-oxc"
path = "src/main.rs"
test = false

[dependencies]
